import { activationStrategy } from "aurelia-router";

export default [
    {
        route: "",
        moduleId: "home/home",
        name: "Home",
        title: "Home",
        nav: true,
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { permission: "Reporting", home: true, embededIframe: true },
    },
    {
        route: "projects",
        moduleId: "../projects/list",
        name: "Projects",
        title: "Projects",
        nav: true,
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { permission: "Project" },
    },
    {
        route: "projects/add",
        moduleId: "../projects/add-edit-project",
        name: "Add Project",
        title: "Add Project",
        nav: false,
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { permission: "Project" },
    },
    {
        route: "projects/edit/:projectId",
        moduleId: "../projects/add-edit-project",
        name: "Edit Project",
        title: "Edit Project",
        nav: false,
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { permission: "Project" },
    },
    {
        route: ["facility", "facility/:facilityId"],
        moduleId: "../facilities/facility",
        name: "Facility",
        title: "Facilities",
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { permission: "Facility" },
    },
    {
        route: "admin",
        moduleId: "../admin/admin",
        name: "AdminModule",
        title: "Admin",
        nav: true,
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { dropdown: true, permission: ["Account", "Facility", "Users"] },
    },
    {
        route: "support",
        moduleId: "../support/support",
        name: "Support",
        title: "Support",
        nav: true,
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { dropdown: true, support: true , permission: "",
          nav: [
            {href: "#rolePermissions", title: "Permissions", name: "Support"},
          ],
      },
    },
    {
        route: "rolePermissions",
        moduleId: "../role-permissions/role-permissions",
        name: "Permissions",
        title: "Permissions",
        nav: false,
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { permission: "Support" },
     },
    {
        route: "facilityPDF/:facilityId",
        moduleId: "../export/facilityPDF",
        name: "FacilityDetailsPDF",
        title: "FacilitiesPDF",
        activationStrategy: activationStrategy.invokeLifecycle,
        auth: true,
        settings: { dropdown: true, support: true, permission: [] },
    },
    {
        route: "access-denied",
        moduleId: "../misc/access-denied",
        name: "AccessDenied",
        title: "Access Denied",
        nav: false,
        activationStrategy: activationStrategy.invokeLifecycle,
        settings: { permission: [] },
    },
    {
        route: "knowledge-center",
        moduleId: "../knowledge-center/knowledge-center",
        name: "KnowledgeCenter",
        title: "Knowlege Center",
        nav: false,
        activationStrategy: activationStrategy.invokeLifecycle,
        settings: { embededIframe: true },
    },
];
